
spec:
  inputs:
    do_build_image:
    do_gen_ip:
    do_sim_regress:
---

###################################################
## image setup
###################################################

build-image:
  extends: [.docker_mixin]
  before_script: !reference [.docker_anchors, docker_prefetch]
  script:
    - docker build docker -f docker/Dockerfile.${DOCKER_PLATFORM}
        --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${CONTAINER_IMAGE}
        --build-arg USER_NAME="${BSG_CI_USER_NAME}"
        --build-arg USER_ID="${BSG_CI_USER_ID}"
        --build-arg GROUP_NAME="${BSG_CI_GROUP_NAME}"
        --build-arg GROUP_ID="${BSG_CI_GROUP_ID}"
        --build-arg OTHER_GROUPS="${BSG_CI_OTHER_GROUPS}"
        -t ${CONTAINER_IMAGE}
  after_script: !reference [.docker_anchors, docker_push]
  rules:
    - if: '"$[[ inputs.do_build_image ]]" =~ "/on_success/"'
    - if: '"$[[ inputs.do_build_image ]]" =~ "/on_event/"'
      changes:
        paths:
          - docker/Dockerfile.${DOCKER_PLATFORM}
          - docker/entrypoint.${DOCKER_PLATFORM}.sh
          - docker/requirements.txt

###################################################
## project definition
###################################################

.project_template:
  extends: [.job_template]
  image: $CONTAINER_IMAGE
  variables:
    # used internally
    GEN_ARTIFACT: "gen"
    GEN_WILDCARD: "gen"
    GEN_PACKAGE: "gen-${DOCKER_PLATFORM}"
    # exported to make sure things go in the right place
    BP_WORK_DIR: "${PROJECT_DIR}/${JOB_WORK_ROOT}/bp-sub-work"
    BP_INSTALL_DIR: "${PROJECT_DIR}/${JOB_WORK_ROOT}/bp-sub-install"
  before_script:
    - !reference [.job_template, before_script]
    - COMMON_INSTALL_DIR="${JOB_COMMON_ROOT}/$(basename ${BP_INSTALL_DIR})"
    - echo "[CI] Initializing common mount @ ${COMMON_INSTALL_DIR}"
    - mkdir -p ${COMMON_INSTALL_DIR} && ls ${COMMON_INSTALL_DIR}

###################################################
## job templates
###################################################

.gen_ip_job:
  extends: [.project_template]
  script:
    - echo "[CI] doing makefile checkout" | tee -a ${JOB_LOG}
    - make -j${CORES_PER_JOB} checkout >> ${JOB_LOG} 2>&1
    - echo "[CI] regenerating rtl" | tee -a ${JOB_LOG}
    - make -j${CORES_PER_JOB} gen >> ${JOB_LOG} 2>&1
    - mv ${BP_INSTALL_DIR} ${JOB_SUCCESS_ROOT}/${GEN_ARTIFACT}
  rules:
    - if: '"$[[ inputs.do_gen_ip ]]" =~ "/on_success|on_event/"'

.scatter_gen_job:
  extends: [.project_template, .api_mixin]
  variables:
    # template variables
    API_PACKAGE_NAME: "${GEN_PACKAGE}"
    API_PACKAGE_VER: "${CI_COMMIT_REF_SLUG}"
    API_PROJECT_ID: "${CI_PROJECT_ID}"
  script:
    - echo "[CI] gathering inputs for ${API_PACKAGE_NAME}" | tee -a ${JOB_LOG}
    - mkdir -p ${API_UPLOAD_ROOT}
    - find ${JOB_DEPS_ROOT} -maxdepth 1 -type d -name ${GEN_WILDCARD}
        -exec rsync --remove-source-files -a {}/ ${API_UPLOAD_ROOT} \; >> ${JOB_LOG} 2>&1
    - !reference [.api_anchors, api_upload]
  rules:
    - if: '"$[[ inputs.do_gen_ip ]]" =~ "/on_success|on_event/"'

.gather_gen_job:
  extends: [.project_template, .api_mixin]
  variables:
    # template variables
    API_PACKAGE_NAME: "${GEN_PACKAGE}"
    API_PACKAGE_VER: "${CI_COMMIT_REF_SLUG}"
    API_PROJECT_ID: "${CI_PROJECT_ID}"
  script:
    - echo "[CI] scattering outputs for ${API_PACKAGE_NAME}" | tee -a ${JOB_LOG}
    - !reference [.api_anchors, api_download]
    - mv ${API_DOWNLOAD_ROOT}/* ${COMMON_INSTALL_DIR}

.sim_regress_job:
  extends: [.project_template]
  variables:
    MODULE: "setme"
    SIM: "setme"
    RUN_SCRIPT: "./ci/common/run-ci.sh"
    TEST_SCRIPT: "./ci/sim-${MODULE}.sh"
  script:
    - echo "[CI] running script for ${TEST_SCRIPT}" | tee -a ${JOB_LOG}
    - ln -nsf ${COMMON_INSTALL_DIR} ${BP_INSTALL_DIR}
    - echo "[CI] doing makefile checkout" | tee -a ${JOB_LOG}
    - make -j${CORES_PER_JOB} checkout >> ${JOB_LOG} 2>&1
    - echo "[CI] running script for ${MODULE} with simulator ${SIM}"
    - ${RUN_SCRIPT} ${TEST_SCRIPT} ${SIM}
  rules:
    - if: '"$[[ inputs.do_sim_regress ]]" =~ "/on_success|on_evnt/" && $DOCKER_PLATFORM == "centos7"'
    - if: '"$[[ inputs.do_sim_regress ]]" =~ "/on_success|on_event/" && $DOCKER_PLATFORM == "ubuntu24.04" && $SIM == "verilator"'

###################################################
## Actual Jobs
###################################################

gen-ip:
  extends: [.gen_ip_job]
  needs: [{job: build-image, optional: true}]

scatter-gen:
  extends: [.scatter_gen_job]
  needs: [gen-ip]

gather-gen:
  extends: [.gather_gen_job]
  needs: [{job: scatter-gen, optional: true}]

sim-regress:
  extends: [.sim_regress_job]
  parallel:
    matrix:
      - MODULE: ["bsg_axil_demux", "bsg_axil_mux", "ethernet"]
        SIM: ["verilator"]
      - MODULE: ["ethernet"]
        SIM: ["vcs"]
  needs: [gather-gen]

